version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin0910  # 'sa' istifadəçisinin şifrəsi
      - MSSQL_PID=Express  # SQL Server versiyası (Express seçilib)
      - MSSQL_DB_NAME=elektra  # SQL Server-da yaradılacaq verilənlər bazası adı
      - MSSQL_DB_USER=Admin  # SQL Server istifadəçisi adı
      - MSSQL_DB_PASSWORD=Admin0910  # SQL Server istifadəçisi şifrəsi
    ports:
      - "1433:1433"  # SQL Server üçün standart port 1433
    volumes:
      - sql_data:/var/opt/mssql  # Məlumatları saxlayacaq bir həcm əlavə olunur
    restart: always  # Konteynerin avtomatik olaraq yenidən başlatılmasını təmin edir

volumes:
  sql_data:  # Məlumat üçün bir həcm yaradılır
