version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-admin
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 102030
    ports:
      - 3306:3306

  adminer:
    hostname: mysql-adminer
    image: adminer
    ports:
      - 8580:8080

  redis:
    image: redis
    container_name: redis
    environment:
      - REDIS_PASSWORD=ProjectMS
    command: [ "redis-server", "--requirepass", "ProjectMS" ]
    ports:
      - 6379:6379
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # Kafka'nın xarici portu (Spring üçün)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093  # INSIDE listener üçün port
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKERCONNECT: "kafka:9092"
volumes:
  db_data:
    driver: local
