apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-admin
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "102030"
      ports:
        - containerPort: 3306
