spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: "102030"
      timeout: 2000
      pool:
        max-idle: 10
        min-idle: 2
    kafka:
      bootstrap-servers: kafka:9092
      producer:
        acks: all
        retries: 3
  datasource:
    url: jdbc:mysql://95.111.238.99/birvolt555
    username: root
    password: 102030
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    version: 21


server:
  port: 8088