spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: "ProjectMS"
      timeout: 2000
      pool:
        max-idle: 10
        min-idle: 2
  datasource:
    url: jdbc:mysql://MYSQL5050.site4now.net/db_a9f58a_birvolt
    username: a9f58a_birvolt
    password: Admin0910
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    version: 21


server:
  port: 8088