apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectms
  template:
    metadata:
      labels:
        app: projectms
    spec:
      containers:
        - name: projectms
          image: heydaroghlu710/projectms:v1
          ports:
            - containerPort: 8088
