apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectms-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectms-app
  template:
    metadata:
      labels:
        app: projectms-app
    spec:
      containers:
        - name: projectms
          image: example-image
          ports:
            - containerPort: 8088